# =========================
# Identidad del proyecto
# =========================
sonar.projectKey=vuln-app
sonar.projectName=Vuln App Wazuh

# =========================
# Código fuente
# =========================
# Analiza API Front
sonar.sources=vuln-api/app,frontend/src
sonar.tests=vuln-api/tests,frontend/tests

# =========================
# Lenguaje
# =========================
sonar.python.version=3.12
sonar.python.coverage.reportPaths=vuln-api/coverage.xml

# Cobertura de Javascript / Vue (Frontend)
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

# =========================
# Exclusiones
# =========================
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/venv/**,**/.venv/**,**/reports/**,frontend/node_modules/**,frontend/dist/**

# =========================
# Encoding
# =========================
sonar.sourceEncoding=UTF-8
