services:
  jenkins:
    build: /home/fabian/vuln-app-wazuh/dev-tools/jenkins
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/fabian/vuln-app-wazuh/dev-tools/reports:/reports 
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - JAVA_OPTS=-Xmx4096m -Xms1024m -XX:+UseG1GC -XX:+ExplicitGCInvokesConcurrent -XX:+ParallelRefProcEnabled -XX:+UseStringDeduplication
    networks:
      - jenkins-network
      - sonar-network
      - app-network

volumes:
  jenkins_data:

networks:
  jenkins-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1460
  sonar-network:
    external: true
    name: sonarqube_sonar-network
  app-network:
    external: true
    name: vuln-app-wazuh_app-network
